version: '3.7'


services:
  web:
    build: .
    container_name: Shop-BLog
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: Shop-Blog
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Adam2004
      POSTGRES_DB: shop_db
    ports: 
      - 5432


volumes:
  postgres_data: