# Generated by Django 4.0.3 on 2022-04-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availibility',
            field=models.CharField(default='in stock', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='new category', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='description', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
