# Generated by Django 4.0.3 on 2022-04-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_availibility_alter_product_image_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
